### ISSUE TITLE
I am unable to compile the code on ubuntu 16.4 LTS after cloning source.

### ISSUE THREAD

**Issue by chetangopal** [pmem/syscall_intercept#105]
avocado@build-u16:~/Dev/preload/syscall_intercept/build$ make
[  0%] Built target check_whitespace
[  2%] Built target cpp_test
[  2%] Built target cstyle
[  7%] Built target syscall_intercept_base_c
[  9%] Built target syscall_intercept_base_asm
[ 10%] Built target syscall_intercept_base_clf
[ 11%] Built target syscall_intercept_unscoped
[ 12%] Generating syscall_intercept_scoped.o
make[2]: localize-hidden: Command not found
[ 13%] Built target generate_syscall_intercept_scoped
[ 13%] Generating syscall_intercept_scoped.o
make[2]: localize-hidden: Command not found
[ 13%] Generating syscall_intercept_scoped.o
make[2]: localize-hidden: Command not found
[ 14%] Linking C shared library libsyscall_intercept.so
gcc: error: syscall_intercept_scoped.o: No such file or directory
CMakeFiles/syscall_intercept_shared.dir/build.make:78: recipe for target 'libsyscall_intercept.so.0.1.0' failed
make[2]: *** [libsyscall_intercept.so.0.1.0] Error 1
CMakeFiles/Makefile2:284: recipe for target 'CMakeFiles/syscall_intercept_shared.dir/all' failed
make[1]: *** [CMakeFiles/syscall_intercept_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by GBuella** [comment]
I see this is your build output:
```make[2]: localize-hidden: Command not found```
I think this is sue to the CMake command we use:
```
add_custom_command(
        OUTPUT syscall_intercept_scoped.o
        COMMAND ${CMAKE_OBJCOPY}
                --localize-hidden
                syscall_intercept_unscoped.o
                syscall_intercept_scoped.o
        DEPENDS syscall_intercept_unscoped.o)
```

Do you have an objcopy that CMake can find? This should be a requirement, but CMake doesn't warn about it.
