### ISSUE TITLE
Unable to locate package libcapstone-dev

### ISSUE THREAD

**Issue by Yoshimaster96** [pmem/syscall_intercept#39]
What it says on the tin. Can't install it.

**Comment by GBuella** [comment]
Could you specify on what distribution this happens?

**Comment by Yoshimaster96** [comment]
Linux Mint Cinnamon 64-bit

**Comment by marcinslusarz** [comment]
Please post cmake log, distribution version, libcapstone-dev package version, output of:
```
dpkg -L libcapstone-dev
```
and
```
cat `dpkg -L libcapstone-dev | grep pc$`
```

**Comment by GBuella** [comment]
By the way I just tried it:
I installed Linux Mint 18.2
https://www.linuxmint.com/edition.php?id=237
I managed to install libcapstone-dev, build syscall_intercept, and run the tests successfully.
If you mean can't `sudo apt install libcapstone-dev`, that likely a problem with that specific Linux Mint installation, and not with syscall_intercept.

**Comment by Yoshimaster96** [comment]
I have Linux Mint 17.3 Cinnamon 64-bit.
Cinnamon version is 2.8.8
Linux kernel is 3.19.0-32-generic
