### ISSUE TITLE
syscall_no_intercept() doesn't match return semantics of real syscall()

### ISSUE THREAD

**Issue by Alex-Richman** [pmem/syscall_intercept#83]
syscall_no_intercept() returns a negated error value rather than setting errno and returning -1 (like syscall() does).
This is documented, and the library does include a syscall_error_code() helper, but it seems a pretty confusing way to do it since syscall_no_intercept() is presented as a drop in replacement for syscall().

For my use I hacked together a little macro to marshal the return values into errno where appropriate, but it'd be nice to see this in the library.  What are your thoughts?
```
#define REAL_SYSCALL(calln, ...) ({                          \
    long __tmp = syscall_no_intercept(calln, ##__VA_ARGS__); \
    errno = syscall_error_code(__tmp);                       \
    if(errno != 0) {                                         \
        __tmp = -1;                                          \
    }                                                        \
    __tmp;                                                   \
})
```

Cheers,
- Alex.

**Comment by marcinslusarz** [comment]
It wouldn't be safe to use it. errno belongs to libc and you should not modify it inside of your syscall handler, because it may confuse libc or an application above (I've seen that happening, see eg https://github.com/pmem/pmemfile/pull/372/commits/7e7dcd7823ce29ab8cb2dee3c26411dc285afed9.

**Comment by Alex-Richman** [comment]
Ah, OK that makes sense.  Thanks for stopping me from burning myself further! ;)

**Comment by GBuella** [comment]
Just to clarify:
"syscall_no_intercept() is presented as a drop in replacement for syscall()." is not wholly true, as `syscall` is a libc wrapper, and `syscall_no_intercept` is presented as a way to make syscalls - which doesn't imply that it would do everything that libs does.
