### ISSUE TITLE
An compilation error

### ISSUE THREAD

**Issue by leebellwind** [pmem/syscall_intercept#85]
Hello,

    I met an error when compiling your project, which is listed below:
    
  make

  ......
   [ 23%] Building ASM object test/CMakeFiles/executable_with_syscall_no_pie.dir/executable_with_syscall.S.o
/root/scylla/syscall_intercept-master/test/executable_with_syscall.S:72:1: error: unknown token in expression
  add rsi, 8 # inc argv
^
make[2]: *** [test/CMakeFiles/executable_with_syscall_no_pie.dir/executable_with_syscall.S.o] Error 1
make[1]: *** [test/CMakeFiles/executable_with_syscall_no_pie.dir/all] Error 2
make: *** [all] Error 2  

    I've installed capstone and upgraded cmake to the version 3.3.2. However, I'm not sure if C99 toolchain has been configured already. When I run cmake, the output is list below:

   -- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= clang

-- The C compiler identification is Clang 3.4.2
-- The CXX compiler identification is GNU 4.8.5
-- The ASM compiler identification is Clang
-- Found assembler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_WERROR
-- Performing Test HAS_WERROR - Success
-- Performing Test HAS_WALL
-- Performing Test HAS_WALL - Success
-- Performing Test HAS_WEXTRA
-- Performing Test HAS_WEXTRA - Success
-- Performing Test HAS_PEDANTIC
-- Performing Test HAS_PEDANTIC - Success
-- Performing Test HAS_NOMFI
-- Performing Test HAS_NOMFI - Success
-- Performing Test HAS_NO9099
-- Performing Test HAS_NO9099 - Failed
-- Performing Test LINKER_HAS_NOSTDLIB
-- Performing Test LINKER_HAS_NOSTDLIB - Success
-- Performing Test HAS_WLFATAL
-- Performing Test HAS_WLFATAL - Success
-- Performing Test HAS_NOUNUSEDARG
-- Performing Test HAS_NOUNUSEDARG - Success
-- Performing Test HAS_ARG_PIE
-- Performing Test HAS_ARG_PIE - Success
-- Performing Test HAS_ARG_NOPIE
-- Performing Test HAS_ARG_NOPIE - Success
-- Performing Test HAS_ARG_NO_PIE
-- Performing Test HAS_ARG_NO_PIE - Failed
-- Performing Test HAS_GCC_ATTR_CONSTR
-- Performing Test HAS_GCC_ATTR_CONSTR - Success
-- Performing Test HAS_GCC_PRAGMA_SYSH
-- Performing Test HAS_GCC_PRAGMA_SYSH - Success
-- Looking for include file elf.h
-- Looking for include file elf.h - found
-- Looking for dladdr
-- Looking for dladdr - found
-- Found Perl: /usr/bin/perl (found version "5.16.3") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/scylla/syscall_intercept-master/my_build_dir

   Thank you!

**Comment by wangjie287** [comment]
Hello, i have met the same question as you! Have you solved this problem?  If you have solved this, could you tell me the solution, thank you very much!

**Comment by GBuella** [comment]
Hm, yes, clang 3.4.2 sounds like a rather old toolchain. It should deal with C99 obviously, but perhaps it doesn't support this assembly syntax?
Can you use a more recent toolchain by any chance?
