### ISSUE TITLE
Why isn't it transparent? Does it change some variables/functions related to a path?

### ISSUE THREAD

**Issue by alexisfrjp** [pmem/syscall_intercept#89]
Hello,

Great job for this library!

I am trying to filter only `stat` syscall with this code (called `example.c`):
```
[...]
    if (syscall_number == SYS_stat) {
        printf("###############intercepted stat syscall######## %s #######\n", arg0); // print the path
    }
    return 1; //Use the default kernel syscall
[...]
```
> int stat(const char *path, struct stat *buf);

1. I copy the file to the include folder to be in the same directory as `libsyscall_intercept_hook_point.h`
2. I run `cc -lsyscall_intercept -fpic -shared example.c -o example.so`
3. Using `LD_PRELOAD=/tmp/example.so app` => app crashes because it can't find some files

Why isn't it transparent? It seems the whole library changes some variables that is used in some apps to get a path.

Just a simple check was to export LD_PRELOAD and the git script for my PS1 of my terminal doesn't work anymore.

Thanks!

**Comment by GBuella** [comment]
Hi @alexisfrjp

Did you install the library using `make install` or `ninja install` ?
Normallly, that should give you the binaries and headers in path that is more convenient.

What do you mean by this more precisely:
"It seems the whole library changes some variables that is used in some apps to get a path."
?
