### ISSUE TITLE
tests compilation error: ustat is deprecated and has been removed from glibc

### ISSUE THREAD

**Issue by ael-code** [pmem/syscall_intercept#90]
`ustat` has been remved from glibc and thus gcc cannot find the `ustat.h` header used in:
 https://github.com/pmem/syscall_intercept/blob/4b3a3b50f9d8d0127a4b39022d78b7369a534673/test/syscall_format.c#L118

Glibc tested version: `2.28`
Gcc tested version: `8.2.1 20180831 (GCC)`

Related issue in Go repository: https://github.com/golang/go/issues/25990

**Comment by GBuella** [comment]
Should be fixed by #88
